logging:
  level:
    root: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
          gateway.route.RouteDefinitionLocator: INFO

spring:
  application:
    name: ms_gateway

  cloud:
    gateway:
      routes:
        - id: ms_product
          uri: lb://msproduct
          predicates:
            - Path=/api/prdms/**, /static/prdms/**

        - id: ms_feedback
          uri: lb://msfeedback
          predicates:
            - Path=/api/fdbms/**, /static/fdbms/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"